language: java
install: mvn install -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6 -DskipTests=true
script: mvn test -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6

#jdk:
#- oraclejdk7

notifications:
  email:
    - o.krasnianskyi@globallogic.com
    # - igor.nesterenko@globallogic.com
    # - borys.kolesnykov@globallogic.com

branches:
  only:
    - develop

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
#  - mvn clean test jacoco:report coveralls:jacoco
